kind: pipeline
type: docker
name: publish


workspace:
  path: /portfolio

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: build
  image: node:15
  commands:
  - yarn
  - yarn build
  - touch build/.nojekyll
  volumes:
  - name: buildFiles
    path: /portfolio/build
- name: publish  
  image: plugins/gh-pages
  volumes:
  - name: buildFiles
    path: /portfolio/build
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_password
    pages_directory: build/

volumes:
- name: buildFiles
  temp: {}
